
export const API_ROUTES = {
  CREATE_USER: "/api/onboarding/create-user",
  UPLOAD_STUDENT_ID: "/api/onboarding/upload-student-id",
  SIGN_IN_EMAIL: "/api/auth/sign-in/email",
  SIGN_IN_PHONE: "/api/auth/sign-in/phone",
  VALIDATE_TOKEN: "/api/auth/validate-token",
  REFRESH_TOKEN: "/api/auth/refresh-token",
  GET_MENU: "/api/menu",
  ADD_TO_CART: "/api/cart/add",
  GET_CART: "/api/cart",
  UPDATE_CART: "/api/cart/update",
  CLEAR_CART: "/api/cart/clear",
  BILLING_PUSH: "/api/billing/push-to-petpooja",
  GET_ALL_COUPONS: "/api/coupon/get-all-coupons",
  SIGN_OUT: "/api/auth/sign-out",
  REMOVE_CART_ITEM: "/api/cart/remove",
  ADD_TO_FAVOURITE: "/api/favourite/add",
  REMOVE_FROM_FAVOURITE: "/api/favourite/remove",
  GET_FAVOURITES: "/api/favourite",
  GET_RECOMMENDATIONS: "/api/home/recommendations",
  GET_BEST_SELLERS: "/api/home/best-sellers",
  GET_NEW_ARRIVALS: "/api/home/new-arrivals",
  POST_RECOMMENDATIONS: "/api/admin/recommendations",
  POST_BEST_SELLERS: "/api/admin/best-sellers",
  POST_NEW_ARRIVALS: "/api/admin/new-arrivals",
  SEND_OTP_TO_PHONE: "/api/auth/phone-number/send-otp",
  VERIFY_OTP_TO_PHONE: "/api/auth/phone-number/verify-otp",
  EDIT_PROFILE: "/api/user/me",
  GET_PROFILE: "/api/user/me",
  PASSWORD_RESET_OTP: "/api/auth/phone-number/request-password-reset",
  RESET_PASSWORD: "/api/auth/phone-number/reset-password",
  GET_WALLET_BALANCE: "/api/wallet/balance",
  GET_WALLET_TRANSACTIONS: "/api/wallet/transactions",
};

    