export type ApiType =
  "CREATE_USER" |
  "UPLOAD_STUDENT_ID" |
  "SIGN_IN_EMAIL" |
  "SIGN_IN_PHONE" |
  "VALIDATE_TOKEN" |
  "REFRESH_TOKEN" |
  "GET_MENU" |
  "ADD_TO_CART" |
  "GET_CART" |
  "UPDATE_CART" |
  "CLEAR_CART" |
  "BILLING_PUSH" |
  "GET_ALL_COUPONS" |
  "SIGN_OUT" |
  "REMOVE_CART_ITEM" |
  "ADD_TO_FAVOURITE" |
  "REMOVE_FROM_FAVOURITE" |
  "GET_FAVOURITES" |
  "GET_RECOMMENDATIONS" |
  "GET_BEST_SELLERS" |
  "GET_NEW_ARRIVALS" |
  "POST_RECOMMENDATIONS" |
  "POST_BEST_SELLERS" |
  "POST_NEW_ARRIVALS" |
  "SEND_OTP_TO_PHONE" |
  "VERIFY_OTP_TO_PHONE" |
  "EDIT_PROFILE" |
  "GET_PROFILE" |
  "PASSWORD_RESET_OTP" |
  "RESET_PASSWORD" |
  "GET_WALLET_BALANCE" |
  "GET_WALLET_TRANSACTIONS" |
  "GET_DINEIN_SLOT_AVAILABILITY" |
  "GET_ORDER_STATUS" |
  "VERIFY_PAYMENT" |
  "CREATE_ORDER";
  
export type TransactionIntentType =
  "intent_create_user" |
  "intent_upload_student_id" |
  "intent_sign_in_email" |
  "intent_sign_in_phone" |
  "intent_validate_token" |
  "intent_refresh_token" |
  "intent_get_menu" |
  "intent_add_to_cart" |
  "intent_get_cart" |
  "intent_update_cart" |
  "intent_clear_cart" |
  "intent_billing_push" |
  "intent_get_all_coupons" |
  "intent_sign_out" |
  "intent_remove_cart_item" |
  "intent_add_to_favourite" |
  "intent_remove_from_favourite" |
  "intent_get_favourites" |
  "intent_get_recommendations" |
  "intent_get_best_sellers" |
  "intent_get_new_arrivals" |
  "intent_post_recommendations" |
  "intent_post_best_sellers" |
  "intent_post_new_arrivals" |
  "intent_send_otp_to_phone" |
  "intent_verify_otp_to_phone" |
  "intent_edit_profile" |
  "intent_get_profile" |
  "intent_password_reset_otp" |
  "intent_reset_password" |
  "intent_get_wallet_balance" |
  "intent_get_wallet_transactions" |
  "intent_get_dinein_slot_availability" |
  "intent_get_order_status" |
  "intent_verify_payment" |
  "intent_create_order";
